# Environment name
name: cp_rul

# Conda channels
channels:
  - conda-forge
  - defaults

# Python dependencies
dependencies:
  - python 
  # - keras
  - pandas 
  - scipy 
  - scikit-learn = 0.21.3 
  - scikit-garden
  - pip
  - matplotlib
  # - pip:
  #   - tensorflow 
    

